name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  shared_preferences: ^2.2.2
  dio: ^5.3.4
  http: ^1.1.0
  json_annotation: ^4.8.1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  intl_utils: ^2.8.6
  flutter_localizations:
    sdk: flutter 
  intl: any
  qr_code_scanner: ^1.0.1
  introduction_screen: ^3.1.12
  story_view: ^0.16.0
  card_swiper: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  lottie: ^2.7.0
  flutter_floating_bottom_bar: ^1.2.0
  build_runner: ^2.4.7
  flutter_gen: ^5.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets\images\splash.png
    - assets\images\stories.png
    - assets\animations\signin.json
    - assets\animations\signup.json
    - assets\animations\loading.json
    - assets\animations\user.json
    

flutter_intl:
  enabled: true
